force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NewEmployeeController.cls
global class NewEmployeeController {
    @AuraEnabled
    global static List<Map<String, String>> getMaritalStatus() {
        
        try {   
            
            List<Map<String, String>> items = new List<Map<String, String>>();
            
            Schema.DescribeFieldResult fd = Employee__c.Marital_Status__c.getdescribe();
            list<Schema.PickListEntry> pc = fd.getpicklistvalues();
            for (Schema.PickListEntry f : pc) {       
                items.add(new Map<String, String>{'value' => f.getvalue() , 'label' => f.getlabel()});
            }      
            
            return items;
            
        } catch(Exception e) {            
            
            AuraHandledException exc = new AuraHandledException('Error in loading.');
            exc.setMessage('Error in loading.');
            system.debug(exc);
            throw exc;
            
        }
    }
}